# This is a basic workflow to help you get started with Actions
name: WDIO-CI
on:
  push:
    branches:
      - develop
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUNNER: '${{secrets.RUNNER}}'
      LOG_LEVEL: '${{secrets.LOG_LEVEL}}'
      NOP_ADMIN_USERNAME: '${{secrets.NOP_ADMIN_USERNAME}}'
      NOP_ADMIN_PASS: '${{secrets.NOP_ADMIN_PASS}}'
    steps:
      - uses: actions/checkout@v3
      - name: Install Chromium
        run: sudo apt-get install chromium-browser
      - name: Use node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Running smoke tests
        run: 'npm run test:smoke-githubActions'
      # Get allure report in github pages with history
      - name: Get Allure History
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Get Allure Report Action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 5
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history