# This is a basic workflow to help you get started with Actions

name: WDIO-CI

# Controls when the workflow will run
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      RUNNER: ${{secrets.RUNNER}}
      LOG_LEVEL: ${{secrets.LOG_LEVEL}}
      NOP_ADMIN_USERNAME: ${{secrets.NOP_ADMIN_USERNAME}}
      NOP_ADMIN_PASS: ${{secrets.NOP_ADMIN_PASS}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Chromium
        run: sudo apt-get install chromium-browser
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Use node.js
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: npm install
      - name: Running smoke tests
        run: npm run test:smoke
